#!/bin/bash

<<COMMENT
Starting with this:

x: 1
z: 2

insert p:3 after x

x: 1
p: 3
z: 2
COMMENT

cat >o1.yaml <<'EOF'
x: 1
z: 2
EOF

cue import --force --outfile=o1.cue o1.yaml

cat >update.cue <<'EOF'
{
    x: _
    p: 3
    z: _
}
EOF

cue eval --force --concrete o1.cue update.cue --out yaml --outfile=o1.yaml
cat o1.yaml
