name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1
      with:
        version: latest
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
      with:
        go-version: '>=1.21'
        cache: false
    - name: Cache testscript
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/go/bin/
          ~/go/bin/testscript
          $GOPATH/bin/
          $GOPATH/bin/testscript
          $HOME/go/bin/
          $HOME/go/bin/testscript
          $USERPROFILE/go/bin/
          $USERPROFILE/go/bin/testscript.exe
        key: ${{ runner.os }}-testscript-${{ hashFiles('**/go.sum') }}
    - name: Install testscript if not cached
      run: |
        if ! command -v testscript &> /dev/null; then
          go install github.com/rogpeppe/go-internal/cmd/testscript@latest
        fi
      shell: bash
    - name: Run tests on non-Windows
      if: runner.os != 'Windows'
      run: testscript -v *.txtar
    - name: Run tests on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: Get-ChildItem -Filter "*.txtar" | ForEach-Object { testscript -v $_.Name }
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47
      with:
        name: test-results-${{ matrix.os }}
        path: |
          test-results/
          *.txtar
        retention-days: 3
        if-no-files-found: error
