name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cue-lang/setup-cue@v1.0.1
      with:
        version: latest
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21'
        cache: true
    - run: go install github.com/rogpeppe/go-internal/cmd/testscript@latest
    - run: |
        testscript *.txtar
