name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os:
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    
    - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1
      with:
        version: latest
    
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'

    - name: Create wrapper script
      shell: cmd
      run: |
        echo @echo off > run.cmd
        echo setlocal > run.cmd
        echo set "LOCALAPPDATA=C:\Users\runneradmin\AppData\Local" >> run.cmd
        echo set "CUE_CACHE_DIR=C:\Users\runneradmin\AppData\Local\cue-cache" >> run.cmd
        echo set "PATH=%PATH%;C:\Users\runneradmin\go\bin" >> run.cmd
        echo mkdir "%LOCALAPPDATA%" 2>nul >> run.cmd
        echo mkdir "%CUE_CACHE_DIR%" 2>nul >> run.cmd
        echo testscript.exe %%* >> run.cmd
        echo exit /b %%ERRORLEVEL%% >> run.cmd

    - run: go install github.com/rogpeppe/go-internal/cmd/testscript@latest

    - name: Run tests
      shell: cmd
      run: |
        set CUE_DEBUG=1
        run.cmd s0100.txtar
      env:
        LOCALAPPDATA: C:\Users\runneradmin\AppData\Local
        CUE_CACHE_DIR: C:\Users\runneradmin\AppData\Local\cue-cache