name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1
      with:
        version: latest
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'
        cache: false
    - run: go install github.com/rogpeppe/go-internal/cmd/testscript@latest
    - name: Run tests
      if: runner.os != 'Windows'
      run: testscript -v *.txtar
    - name: Run tests
      if: runner.os == 'Windows'
      shell: pwsh
      run: Get-ChildItem -Filter "*.txtar" | ForEach-Object { testscript -v $_.Name }
