name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os:
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    
    - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1
      with:
        version: latest
    
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'

    - name: Create wrapper script
      shell: pwsh
      run: |
        $scriptContent = @'
        @echo off
        setlocal enabledelayedexpansion
        set "HOME=%USERPROFILE%"
        set "LOCALAPPDATA=%USERPROFILE%\AppData\Local"
        set "CUE_CACHE_DIR=%LOCALAPPDATA%\cue-cache"
        set "PATH=%PATH%;%USERPROFILE%\go\bin"
        
        if not exist "%LOCALAPPDATA%\cue-cache" mkdir "%LOCALAPPDATA%\cue-cache"
        
        set FORCE_LOCAL_APPDATA=1
        
        testscript.exe %*
        exit /b %ERRORLEVEL%
        '@
        
        $scriptContent | Out-File -FilePath "run.cmd" -Encoding ascii

    - run: go install github.com/rogpeppe/go-internal/cmd/testscript@latest

    - name: Run tests
      shell: cmd
      run: |
        set USERPROFILE=C:\Users\runneradmin
        set LOCALAPPDATA=C:\Users\runneradmin\AppData\Local
        set CUE_DEBUG=1
        set HOME=C:\Users\runneradmin
        set CUE_CACHE_DIR=C:\Users\runneradmin\AppData\Local\cue-cache
        set PATH=%PATH%;C:\Users\runneradmin\go\bin
        
        if not exist "%LOCALAPPDATA%\cue-cache" mkdir "%LOCALAPPDATA%\cue-cache"
        
        run.cmd s0100.txtar