name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os:
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    
    - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1
      with:
        version: latest
    
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'

    - name: Set up environment variables
      shell: pwsh
      run: |
        echo "LOCALAPPDATA=C:\Users\runneradmin\AppData\Local" >> $env:GITHUB_ENV
        echo "CUE_CACHE_DIR=C:\Users\runneradmin\AppData\Local\cue-cache" >> $env:GITHUB_ENV
        
        # Create directories if they don't exist
        New-Item -Path "C:\Users\runneradmin\AppData\Local" -ItemType Directory -Force
        New-Item -Path "C:\Users\runneradmin\AppData\Local\cue-cache" -ItemType Directory -Force

    - run: go install github.com/rogpeppe/go-internal/cmd/testscript@latest

    - name: Run tests
      shell: pwsh
      run: |
        $Env:CUE_DEBUG = "1"
        $Env:CUEROOT = (Get-Command cue).Path | Split-Path -Parent
        Write-Host "Using LocalAppData: $Env:LOCALAPPDATA"
        Write-Host "Using CUE_CACHE_DIR: $Env:CUE_CACHE_DIR"
        Write-Host "Using CUEROOT: $Env:CUEROOT"
        testscript s0100.txtar
      env:
        LOCALAPPDATA: C:\Users\runneradmin\AppData\Local
        CUE_CACHE_DIR: C:\Users\runneradmin\AppData\Local\cue-cache
        CUE_DEBUG: "1"
        CUEROOT: C:\hostedtoolcache\windows\cue\latest\x64