name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT

jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        os:
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    
    - uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1
      with:
        version: latest
    
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'

    - name: Set up environment variables
      shell: cmd
      run: |
        echo "LOCALAPPDATA=C:\Users\runneradmin\AppData\Local" >> %GITHUB_ENV%
        mkdir "C:\Users\runneradmin\AppData\Local" 2>nul
        echo "CUE_CACHE_DIR=C:\Users\runneradmin\AppData\Local\cue-cache" >> %GITHUB_ENV%
        mkdir "C:\Users\runneradmin\AppData\Local\cue-cache" 2>nul

    - run: go install github.com/rogpeppe/go-internal/cmd/testscript@latest

    - name: Run tests
      shell: cmd
      run: |
        set CUE_DEBUG=1
        echo "Using LocalAppData: %LOCALAPPDATA%"
        testscript s0100.txtar
      env:
        LOCALAPPDATA: C:\Users\runneradmin\AppData\Local
        CUE_CACHE_DIR: C:\Users\runneradmin\AppData\Local\cue-cache